esphome:
  name: hp-pulsereader

esp8266:
  board: nodemcu
  # Enable this if you want to store the total number of pulses in case of a power outage
  restore_from_flash: true 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "hp-pulsereader"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0 # disable logging over uart

# Enable Home Assistant API
api:
  encryption:
    key: !secret hass_api_key

ota:
  password: !secret ota_password

# Pnp OC transistor meter output connected to GPIO12 and GND
# GARO GNM3D Led output: 1000 pulses/kWh
# GARO GNM3D(-pulse) switch output 9 (GND) and 10 (sig): 1000 pulses/kWh (100 by default, re-qomfigurable menu P12). 
sensor:
  - platform: pulse_counter
    pin:
      number: GPIO4
      inverted: true
      mode:
        input: true
        pullup: true
    unit_of_measurement: 'W'
    name: 'Power Meter HP House'
    device_class: power
    filters:
      - multiply: 60  # (60s/1000 pulses per kWh)

    total:
      unit_of_measurement: 'Wh'
      name: 'Energy Meter HP House'
      device_class: energy
      filters:
        - multiply: 1  # (1000 pulses per kWh)

